openapi: 3.0.0
info:
  title: 3-D Printer API
  description: This API extends the function of the Ultimaker 3s API
  version: 0.1.0
paths:
  /get_jobs:
    get:
      summary: Get a list of all the previous jobs done on the system.
      description: Allows the user to search the database for all previous job filename, start and end times, current status, and printer.

        The return type is a JSON array of filename/detail pairs represented as a dict

      responses:
        '200':
          description: A JSON array of name/details pairs represented as a dict

          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: filename
                  details:
                    type: array
                    description: array contains all other data about job including printer name, start time, end time, and status

